Pages en kowiki
ko-nlp/Korpora pull request #164
Opened 2020-11-10 17:00 UTC by warnikchow

## 1. 해당 PR은 어떤 내용인가요?

## 2. PR과 관련된 이슈가 있나요?

2020-11-11 21:02 UTC, lovit commented on en-docs/corpuslist/kowikitext.md
> +Korean WikiText is the Korean Wikipedia data, refined to text format and released by lovit@github.
@warnikchow 님, 이 부분이 고민이신거죠? 아래처럼 수정하면 어떨까요?

```
"Korean WikiText" is wikitext format dataset which consists only with header and text of wikipedia.
The dataset is refined and released by lovit@github
```

2020-11-16 06:35 UTC, hank110 requested changes
몇 가지 문법적 측면에서 comment 남겨놨습니다.
다음과 같이 약간의 수정은 어떨까요?

2020-11-16 06:35 UTC, hank110 commented on en-docs/corpuslist/kowikitext.md
> +Data structure is as:
is as follows:

2020-11-16 06:35 UTC, hank110 commented on en-docs/corpuslist/kowikitext.md
> +If you want to download it in other path, please assign `root_dir=custom_path` when you execute fetch function.
other path --> another path

2020-11-16 06:35 UTC, hank110 commented on en-docs/corpuslist/kowikitext.md
> +Korean WikiText is the Korean Wikipedia data, refined to text format and released by lovit@github.
위에 커멘트 주신 내용을 기반으로 조금 수정을 했는데 어떠실까요?

```
"Korean WikiText" is a wikitext format dataset which consists of only the headers and texts of wikipedia.
The dataset is refined and released by lovit@github
```

2020-11-16 08:53 UTC, hank110 approved these changes

2020-11-16 12:50 UTC, merged